---
all:
  vars:
    ansible_ssh_user: root
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    children:
      web:


dev:
  hosts:
    dev.chaolopezpa.com:

test:
  hosts:
    test.chaolopezpa.com:

prod:
  hosts:
    www.chaolopezpa.com:

