---

- file:
    state: directory
    path: "{{ wordpress_basedir }}"

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
      - { src: "docker-compose.yml.j2", dest: "{{ wordpress_basedir }}/docker-compose.yml" }
